-- Migration 052: no-op.
--
-- The schema corrections originally intended here (composite unique constraint,
-- composite indexes, per-operation RLS policies) were incorporated directly into
-- migrations 050 and 051 before those migrations were first applied to production.
-- No changes are required.
